import "../styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header";
import Footer from "../components/footer";
const Icon = "/next.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Demo Project",  
  description: "Generated by create next app",
  icons: Icon,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
